name: autotests

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  autotests:
    runs-on: ubuntu-latest
    container: golang:1.23

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup go deps
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go mod tidy

      - name: tests
        run: |
          go test ./...
